### ISSUE TITLE
Cannot upload backgrounds (Error 500)

### ISSUE THREAD

**Issue by jcn50** [YunoHost-Apps/vikunja_ynh#17]
### Describe the bug

It is impossible to upload backgrounds (Error 500).
**I have manually updated the API + Front-end to Version: 0.18.1 and the issue remains, so it is a Nginx or YunoHost configuration problem!**

### Context

- Hardware: VPS bought online
- YunoHost version: 4.3.6 (stable)
- I have access to my server: through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 

### Steps to reproduce

Try to upload a background image in a list > "Set Background".

### Expected behavior

No errors.

### Logs

Many CSS & JS errors in the Console:
```
Failed to load resource: the server responded with a status of 404 /ynhtheme/custom_portal.js
Refused to apply style from '/ynh_overlay.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled. /login:1 
Refused to apply style from '/ynhtheme/custom_overlay.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled. /login:1 
Refused to apply style from '/ynh_overlay.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled. /login:1
Refused to apply style from '/ynhtheme/custom_overlay.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled. background:1 
Refused to apply style from '/ynh_overlay.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled. background:1 
Refused to apply style from '/ynhtheme/custom_overlay.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.  background:1
```

**Comment by jcn50** [comment]
Found the issue, you need to run this command and it's FIXED! Please add this to the installation file too:

`mkdir /opt/vikunja/files && chown -R vikunja:www-data /opt/vikunja/files`

**Comment by ericgaspar** [comment]
Thanks for the fix!
#18 should fix the issue.
upgrade need to be tested...
```
sudo yunohost app upgrade vikunja -u https://github.com/YunoHost-Apps/vikunja_ynh/pull/18 --force
```
