### ISSUE TITLE
Install fails on ARM

### ISSUE THREAD

**Issue by Tagadda** [YunoHost-Apps/vikunja_ynh#21]
### Describe the bug

The .deb published by Vikunja only support amd64, therefore the package can't install on non-amd64 platform.

### Steps to reproduce

Try to install the package on a Raspberry Pi.

### Possible solution

* Have a specific case on non-amd64 platform to use binary from https://dl.vikunja.io/api/0.18.1

OR

* Use a binary from https://dl.vikunja.io/api/0.18.1 in any case

### Logs

Some logs from users on the forum and chat
* https://paste.yunohost.org/raw/ofoseravoc
* https://paste.yunohost.org/raw/pijigigoxa

**Comment by DorianBDev** [comment]
#22 should fix that (tested on my arm64 server).

**Comment by ex06** [comment]
Even after the merge didn't immediatly worked because it kept trying to install the amd one, but today i successfully installed it on my Pi4!

**Comment by ericgaspar** [comment]
fix with https://github.com/YunoHost-Apps/vikunja_ynh/pull/22
