### ISSUE TITLE
The config.yml is not in /opt/vikunja/config.yml

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/vikunja_ynh#30]
The readme points to that path but there is no such file in that path. However I see it here: `/etc/vikunja` and here `/etc/yunohost/apps/vikunja`. So which one is the correct one to edit? Thanks!

**Comment by tio-trom** [comment]
Ok. Make sure you perhaps update the readme :)

**Comment by ericgaspar** [comment]
Feel free to push a PR to correct the readme :)

**Comment by tio-trom** [comment]
I did. I hope I did it correctly.

**Comment by ericgaspar** [comment]
Rereading the doc, I wonder if the configuration file should not be with the binary... I don't remember why I put it in `etc/`...
