### ISSUE TITLE
New options on config template file > error after the migration

### ISSUE THREAD

**Issue by AvocatDuDiable** [YunoHost-Apps/vikunja_ynh#39]
Hello all, 

I'm blocked on my new version of Vikunja package. 
I would like to add more options on the config panel. I already add some options where keys are already present on the template file. 

But the current default config file of Vikunja has now new options. For example enable_userdeletion. 
I added it on : 
- template file 
- install script file 
- upgrade script file 
- config panel file 

It's working when you install the app for the first time. 
But it's not working when you upgrade. When I go to config panel, I have a 500 error because new options has not been added by the upgrade script. 

I think to have follow the example package and the "guidlines" but maybe I miss something. 

The code is on my repository in the vnext branch. [CODE](https://github.com/AvocatDuDiable/vikunja_ynh/tree/vnext)

Can someone help me ? 

Thanks a lot

**Comment by ericgaspar** [comment]
I guess you have to generate the config file during upgrade...

Add this after L.171 in the upgrade script:

```
#=================================================
# UPGRADE A CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading a configuration file..." --weight=1

redis_db=$(ynh_redis_get_free_db)
ynh_add_config --template="../conf/config.yml" --destination="$backend_path/config.yml"

chmod 400 "$backend_path/config.yml"
chown $app:$app "$backend_path/config.yml"
```

**Comment by AvocatDuDiable** [comment]
Thanks @ericgaspar ! It works.
