### ISSUE TITLE
Can't login in web if login in SSO

### ISSUE THREAD

**Issue by dumprop** [YunoHost-Apps/vikunja_ynh#4]
After login I catch that (session reset)
![image](https://user-images.githubusercontent.com/34004367/129457359-26aaf353-c5ec-4020-9fae-c8f71112efc6.png)

DEBUG:
1) login
![image](https://user-images.githubusercontent.com/34004367/129457394-c1a854d4-d131-42ce-b0f4-c1618c7f6966.png)
2) /api/v1/user/token
![image](https://user-images.githubusercontent.com/34004367/129457459-d5db5be4-b8e4-4446-950c-5018629e77a0.png)
3) response
![image](https://user-images.githubusercontent.com/34004367/129457479-33b0a105-a889-47c4-ad3d-564e00f3e616.png)
Same with /api/v1/user

FIX: log out from yunohost
So desktop app works correctly

**Comment by ericgaspar** [comment]
what is you do:
- in the login page, click `change` blue link `(Sign in to your Vikunja account on vikunja.domain.ltd) change` 
- set the path to API -> `vikunja.domain.ltd/api/v1` the change button
- enter username/password

**Comment by dumprop** [comment]
> 
> 
> what if you do:
> 
>     * in the login page, click `change` (blue link) `(Sign in to your Vikunja account on vikunja.domain.ltd) change`
> 
>     * set path to API -> `vikunja.domain.ltd/api/v1`
> 
>     * enter username/password

Now I see my username (there no session reset)
But there no any my information (abouts tasks)
![image](https://user-images.githubusercontent.com/34004367/129492935-a40e895c-308e-44f5-81aa-1ca70087ef86.png)

**Comment by joe-hudson** [comment]
I had the same issue. Setting the permissions to "all users" cleared it up. It would be nice to be able to keep this obscured from the world, but not a deal-breaker. Nice work @ericgaspar

**Comment by alexAubin** [comment]
That sounds similar to https://github.com/YunoHost-Apps/mastodon_ynh/issues/43 and other issues where the SSO conflicts with the app's internal auth library

Should be fixed if we add --auth_header="false" like in https://github.com/YunoHost-Apps/peertube_ynh/blob/master/scripts/install#L263 for example

**Comment by ericgaspar** [comment]
The issue should be fixed with #6

**Comment by dumprop** [comment]
Currently seems I still have this problem .. :(

**Comment by TheNomad11** [comment]
Same error for me as well

**Comment by ericgaspar** [comment]
Could you add a little more context to the problem you are facing?

**Comment by dumprop** [comment]
> 
> 
> Could you add a little more context to the problem you are facing?
> edit: on my installed Vikunja, the missing or malformed jwt warning has disappeared

![image](https://user-images.githubusercontent.com/34004367/130359432-9ebcc9e6-1d2f-48bd-9409-72c076d55c5e.png)
![image](https://user-images.githubusercontent.com/34004367/130359448-61db4524-36d6-40d5-8019-a152fa525315.png)

![image](https://user-images.githubusercontent.com/34004367/130359347-01f8ee08-8ad5-4144-b8a3-b7638155c9e7.png)

![image](https://user-images.githubusercontent.com/34004367/130359316-0fc9ea2c-fffc-4a4a-9c21-3f5e340bcc9f.png)
Seems same problem (deleted SSO cookies in local storage and all are working)

**Comment by dumprop** [comment]
![image](https://user-images.githubusercontent.com/34004367/130366021-80929213-2770-43dc-9f90-653a498082fa.png)
In fact there still YNH cookies in requests, that breaks vikunja

**Comment by dumprop** [comment]
Seems fixed on 0.18.1~ynh2
