### ISSUE TITLE
Admin Panel Not Working after upgrade YNH 4.x -> YNH 11

### ISSUE THREAD

**Issue by MokuJinJin** [YunoHost-Apps/vikunja_ynh#41]
### Describe the bug

Just after upgrading, i can't login, i can't access to the app config.

Error form login : 
```text
o.response.data is undefined
```

and in dev tools
```text
GET https://vikunja.mokujin.org/api/v1/info           [HTTP/1.1 502 Bad Gateway 0ms]

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://yuno.mokujin.org/yunohost/sso/?r=aHR0cHM6Ly92aWt1bmphLm1va3VqaW4ub3JnLw==. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 405.
```

Error from app config : 
```text
Error: "500" Internal Server Error

Action: "GET" /yunohost/api/apps/vikunja/config-panel?full&locale=en

Error message:
Failed to read config panel values.
```

### Context

- Hardware: Old laptop or computer
- YunoHost version: 11.0.9.9
- I have access to my server: All access
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- If upgrading, current package version: 0.19.0~ynh1

### Steps to reproduce

- *If the error occurs in your browser, explain what you did:*
   1. Go to Yunohost Admin
   2. Click on Application, Vikunja, then Config Panel
   3. *See error*

- *If the error occurs in your browser, explain what you did:*
   1. Go to Yunohost User
   2. Click on Vikunja, Try to login
   3. *See error*

### Expected behavior

Try to login, or change some config

### Logs

Logs from vikunja update *BEFORE* upgrade YNH : https://paste.yunohost.org/raw/ehobihuciy

Error from config panel
![image](https://user-images.githubusercontent.com/5294669/186010419-92da71e9-bfb3-4822-9b55-4eb333434854.png)

**Comment by MokuJinJin** [comment]
I manage to log in 🎉 
on login screen, i change Vikunja URL.
It was `http://******/apiapi/v1` i change it to `http://******/api/v1` and it works.

I still don't have access to admin config panel.

**Comment by ericgaspar** [comment]
Should be fixed. Please reopen if needed.
