### ISSUE TITLE
"Error While refreshing user info" coupled with API Route issues when signing in Chrome and Firefox

### ISSUE THREAD

**Issue by CtheCondor** [YunoHost-Apps/vikunja_ynh#56]
### Describe the bug
When accessing the hosted Application on chrome and firefox I am getting an API Route issue predicated by "Error While refreshing user info"
![image](https://github.com/YunoHost-Apps/vikunja_ynh/assets/70120966/ccee9d37-71f3-4049-84cb-7a328e754742)

### Context

- Hardware: Linode Server Node
- YunoHost version: 11.2.5 (stable)
- I have access to my server: All of the above [ssh,web]
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no; stock install
- Using, or trying to install package version/branch: vikunja 0.21.0~ynh3
- 
### Steps to reproduce
   1. *Go to 'tasks.mydomain.xyz' and sign in using created username and password from first install.
   2. Close browser application
   3. Re-open browser and return to same URL and gets the above error either immediately or after signing in
   4. *See error above*

If I clear all cookies and site settings for the domain; I can usually sign in or if I am on private browsing mode from the beginning oddly enough.

### Expected behavior
I would expect to be able to login consistently without having to clear cookies and site settings nearly daily or even a few times a day if my browser closes ¯\_(ツ)_/¯

### Logs
*When an operation fails, YunoHost provides a simple way to share the logs.*
I checked the logs section and there are no yunohost created logs but when I check the vikunja service logs I get the following if I sanitize my username/domain information from here but it just shows that there are pairs of HTML code 200 and 401 when trying to login. 
https://paste.yunohost.org/telatajoci

**Comment by ericgaspar** [comment]
You may want to test the testing branch to see if it fixes the issue.
```
sudo yunohost app upgrade vikunja -u https://github.com/YunoHost-Apps/vikunja_ynh/tree/testing
```

**Comment by CtheCondor** [comment]
> You may want to test the testing branch to see if it fixes the issue.
> 
> ```
> sudo yunohost app upgrade vikunja -u https://github.com/YunoHost-Apps/vikunja_ynh/tree/testing
> ```

This does indeed seem to work! This is the first `yunohost app upgrade` command I have locally run. Once this testing branch is published; will I need to do anything to re-align?

**Comment by ericgaspar** [comment]
yes, it should

**Comment by CtheCondor** [comment]
As this has resolved my issue; shall I close this ticket or shall I leave that for you?
