### ISSUE TITLE
After update to version: 0.24.1~ynh1 all projects are empty

### ISSUE THREAD

**Issue by intellekta** [YunoHost-Apps/vikunja_ynh#70]
after the update all my project are empty without any tasks
the about info in the browser shows the old Version: v0.22.1
is it possible that the api 22 is not compatible with 24?
is there an API update or 24?
thanks in advance

**Comment by stilobique** [comment]
Can you share your install log, and your log service application ?

**Comment by intellekta** [comment]
i found the only failed service is mongod, vikunja runs, the logs are attached.
where can i find the install log?
[2024-07-29_uc-yunohost-service.txt](https://github.com/user-attachments/files/16411098/2024-07-29_uc-yunohost-service.txt)

**Comment by intellekta** [comment]
i can start mongod but under service it is stopped.
when i try tools logs i got:
unoHost encountered an internal error
Really sorry about that.
You should look for help on [the forum](https://forum.yunohost.org/) or [the chat](https://chat.yunohost.org/) to fix the situation, or report the bug on [the bugtracker](https://github.com/YunoHost/issues).
The following information might be useful for the person helping you:
Error: "500"

Action: "GET" /yunohost/api/logs?limit=25&with_details&locale=en

Error message:
Unexpected server error

Traceback

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 450, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 574, in process
    return func(**arguments)
  File "/usr/lib/python3/dist-packages/yunohost/log.py", line 135, in log_list
    _update_log_parent_symlinks()
  File "/usr/lib/python3/dist-packages/yunohost/log.py", line 90, in _update_log_parent_symlinks
    logs = glob.iglob("*" + METADATA_FILE_EXT, root_dir=OPERATIONS_PATH)
TypeError: iglob() got an unexpected keyword argument 'root_dir'

**Comment by intellekta** [comment]
After update from .22 to .24 tools logs works fine

**Comment by intellekta** [comment]
https://paste.yunohost.org/raw/safucuxihi

**Comment by intellekta** [comment]
the mongod is assigned to the wekan app, when i try to go to the wekan url im redirected to /yunohost/sso

**Comment by GTHeyyy** [comment]
Hi!

I have the same problem. Even on a fresh installation.

**Comment by CodeShakingSheep** [comment]
Hi @intellekta @GTHeyyy ,
I opened a PR https://github.com/YunoHost-Apps/vikunja_ynh/pull/71 which fixes the single source installation together with @ericgaspar . The PR was merged into testing branch which has been merged into master. However, the version hasn't been increased yet. I will open a new PR for that now and then with the next update your issues should be fixed.

**Comment by intellekta** [comment]
Yeah, it works, front end shows 24.1 too.
Many Thanks.
